### ISSUE TITLE
Update the frontpage with logo and sponsors

### ISSUE THREAD

**Issue by kristjanmik** [CommunityFundIS/web#15]

**Comment by asgeirvisir** [comment]
Logo for various use cases.

[communityFundLogo.zip](https://github.com/CommunityFundIS/web/files/847549/communityFundLogo.zip)

**Comment by kiddi** [comment]
I've sent messages to SI, Frumtak and Kaptio about their logos. Meanwhile, here is Lagahvoll, Tempo, and Northstack

[Lagahvoll Merki.pdf](https://github.com/CommunityFundIS/web/files/848893/Lagahvoll.Merki.pdf)

![tempo](https://cloud.githubusercontent.com/assets/8244385/24016284/78fb761c-0a83-11e7-89fc-68e773a2a5bf.png)

![northstack unstacked](https://cloud.githubusercontent.com/assets/8244385/24016304/8b099f32-0a83-11e7-8748-1ae16fa47df1.png)

**Comment by kiddi** [comment]
![kaptio_logo](https://cloud.githubusercontent.com/assets/8244385/24081234/c6c0faae-0ca7-11e7-98fe-0a5e762b1d1f.png)
<img width="177" alt="screenshot 2017-03-19 13 25 53" src="https://cloud.githubusercontent.com/assets/8244385/24081237/cf32dc66-0ca7-11e7-957c-dfe0a92906cc.png">

**Comment by kiddi** [comment]
Only missing Frumtak Ventures.
