### ISSUE TITLE
Finalize branding

### ISSUE THREAD

**Issue by kiddi** [CommunityFundIS/web#42]
We should decide on slogan, typefaces, and basic color scheme.

**Slogan suggestion:**
Enabling the Icelandic tech community

Thoughts?

**Comment by kiddi** [comment]
@kristjanmik @asgeirvisir

Thoughts?

**Comment by asgeirvisir** [comment]
I can create a little branding brochure/folder if you guys want. With a colour palette, typefaces, sponsor slide for keynote etc.

I'll leave the slogan in your capable hands.

**Comment by kiddi** [comment]
That would be BEAUTIFUL :)

**Comment by kristjanmik** [comment]
Stale, closing :)
