### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by kristjanmik** [CommunityFundIS/web#6]
We need to set up automatic deployment so that changes in master get pushed to production

**Comment by johannth** [comment]
Where do we currently deploy this? Do we use deployToAzureWebApps to deploy?

**Comment by kristjanmik** [comment]
No, that is from the boilerplate. Our setup is at AWS, and we will most likely go with your suggestion of using ElasticBeanstalk.

**Comment by johannth** [comment]
We've setup CI: tests on every branch and automatic deployments on merges to master using CodeShip.
